# GitHub Plus Light theme for Kitty

# Basic colors
foreground              #333333
background              #ffffff
selection_foreground    #24292e
selection_background    #e4e6f1

# Cursor colors
cursor                  #5c78e2
cursor_text_color       #ffffff

# URL colors
url_color               #005bc5

# Border colors
active_border_color     #005bc5
inactive_border_color   #e1e4e8
bell_border_color       #d3a040

# Tab bar colors
active_tab_foreground   #24292e
active_tab_background   #ffffff
inactive_tab_foreground #586069
inactive_tab_background #f6f8fa
tab_bar_background      #f6f8fa

# Marks
mark1_foreground        #ffffff
mark1_background        #005bc5
mark2_foreground        #ffffff
mark2_background        #6f42c1
mark3_foreground        #ffffff
mark3_background        #0ac7d7

# Black
color0  #414141
color8  #989898

# Red
color1  #d73949
color9  #fa6e71

# Green
color2  #90d159
color10 #35d61b

# Yellow
color3  #f7c400
color11 #ffca39

# Blue
color4  #005bc5
color12 #1b22d6

# Magenta
color5  #ff73fd
color13 #ff00ff

# Cyan
color6  #0ac7d7
color14 #3bd6e7

# White
color7  #bfbfbf
color15 #e0e0e0
